name       : xrandr
version    : 1.5.1
release    : 6
source     :
    - https://www.x.org/releases/individual/app/xrandr-1.5.1.tar.xz : 7bc76daf9d72f8aff885efad04ce06b90488a1a169d118dea8a2b661832e8762
homepage   : https://gitlab.freedesktop.org/xorg/app/xrandr
license    : MIT
component  : xorg.apps
summary    : Command line interface to X11 Resize, Rotate, and Reflect (RandR) extension
description: |
    xrandr is a primitive command line interface to X11 Resize, Rotate, and Reflect (RandR) extension.
builddeps  :
    - pkgconfig(xrandr)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
