name       : xrandr
version    : 1.5.0
release    : 4
source     :
    - https://www.x.org/releases/individual/app/xrandr-1.5.0.tar.gz : ddfe8e7866149c24ccce8e6aaa0623218ae19130c2859cadcaa4228d8bb4a46d
license    :
    - MIT
summary    : xrandr
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
description: |
    xrandr
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
