name       : xrandr
version    : 1.5.1
release    : 5
source     :
    - https://www.x.org/releases/individual/app/xrandr-1.5.1.tar.xz : 7bc76daf9d72f8aff885efad04ce06b90488a1a169d118dea8a2b661832e8762
license    :
    - MIT
component  : xorg.apps
summary    : xrandr
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
description: |
    xrandr
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
